epochs = 10  
batch_size = 8  # Increased for Colab GPU (can go higher if you have memory)
image_height = 256 
image_width = 256
train_num = 9588  # All images from set03 + set05
learning_rate = 1e-4
learning_rate_d = 1e-4
log_interval = 20  # Increased since we have more batches
save_model_path = "/content/models/"  # Local storage
